<?php
function gerlv_social_theme() {
    return array(
        'gerlv_social_retweet' => array(
            'arguments' => array(NULL)
        ),
        'gerlv_social_like' => array(
            'arguments' => array('url' => false)
        ),
    );
}

function theme_gerlv_social_like($url = false) {
    if(!$url) {
        $url = check_plain(request_uri());
    }
    $url = urlencode($url);
    return '<iframe src="http://www.facebook.com/plugins/like.php?href='.$url.'&amp;layout=box_count&amp;show_faces=false&amp;width=450&amp;action=recommend&amp;font&amp;colorscheme=light&amp;height=65" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:65px;" allowTransparency="true"></iframe>';
}

function theme_gerlv_social_retweet() {
    return '<script type="text/javascript">
tweetmeme_source = \'gerlv\';
tweetmeme_service = \'bit.ly\';
</script>
<script type="text/javascript" src="http://tweetmeme.com/i/scripts/button.js"></script>';
}